version: '2'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    # Ensure the read and write access
    privileged: true
    volumes:
      - ../:/var/www/html/:rw
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/:/var/log/nginx/:rw
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    links:
      - php74:fpm74

  php74:
    build: ./php/php74/
    expose:
      - "9000"
    privileged: true
    volumes:
      - ../:/var/www/html/:rw
      - ./conf/php72/php.ini:/usr/local/etc/php/php.ini:rw
      - ./conf/php72/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php-fpm/:/var/log/php-fpm/:rw
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    links:
      - mysql:mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    privileged: true
    volumes:
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./mysql/:/var/lib/mysql/:rw
      - ./log/mysql/:/var/log/mysql/:rw
      - ./sources.list.stretch:/etc/apt/sources.list:ro
    environment:
      - SET_CONTAINER_TIMEZONE='true'
      - CONTAINER_TIMEZONE=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD="chenliyi123"

  node:
    image: "node:12"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./node-app:/home/node/app/:rw
    environment:
      - NODE_ENV=production
      - SET_CONTAINER_TIMEZONE='true'
      - CONTAINER_TIMEZONE=Asia/Shanghai
    expose:
      - "8081"
    command: "npm start"
